// ─────────────────────────────────────────────────────────────────────────────
//  Frases de los subtítulos del escritorio (rice-subs). Una por línea.
//  Para sacar una: borrá su línea. Para sumar: agregá "Tu frase.", con coma.
//  Los cambios se ven al reiniciar:  qs kill -c rice-subs; uwsm app -- qs -c rice-subs
// ─────────────────────────────────────────────────────────────────────────────
var list = [
    "OK computer.",
    "Okey dokey.",
    "See you, space cowboy.",
    "Whatever happens, happens.",
    "Let's jam.",
    "Bang.",
    "Present day. Present time.",
    "Close the world. Open the next.",
    "I mustn't run away.",
    "Pattern blue.",
    "Synchronization stable.",
    "Congratulations.",
    "Welcome home.",
    "Signal lost.",
    "No signal.",
    "Please stand by.",
    "Stay tuned.",
    "We'll be right back.",
    "Tune in tomorrow.",
    "End of transmission.",
    "Over and out.",
    "Copy that.",
    "Roger.",
    "Say again?",
    "Hello? Hello?",
    "Dial tone.",
    "Are you still there?",
    "Who's there?",
    "Did you hear that?",
    "Can you feel it?",
    "Wake up.",
    "You're late.",
    "Time to go.",
    "Go home. It's late.",
    "It's 3 a.m. somewhere.",
    "Nothing is real after midnight.",
    "The city never sleeps. Neither do I.",
    "Rain again.",
    "Coffee's cold again.",
    "Another day, another bounty.",
    "Keep the change.",
    "Not bad, kid.",
    "Too late for apologies.",
    "Not now. Not ever.",
    "I'm fine. Really.",
    "Don't look at me like that.",
    "Don't forget me.",
    "Hold your breath.",
    "Smile for the camera.",
    "I'll be watching.",
    "Somebody turn the lights off.",
    "Lights. Camera. Nothing.",
    "Roll tape.",
    "Rewind the tape.",
    "Cut.",
    "Out of frame.",
    "The end?",
    "Insert disk 2.",
    "Press any key.",
    "Loading memories...",
    "Still loading.",
    "Saving... do not turn off.",
    "Memory full.",
    "Battery low.",
    "Dreaming in 16 colors.",
    "Static on every channel.",
    "The Wired is listening.",
    "Ghost in the wires.",
    "All systems nominal.",
    "Everything is under control.",
    "This is not a drill.",
    "The sun is a liar.",
    "Remember the stars.",
    "The tide is coming in.",
    "One more time.",
    "Hmm.",
    "...",
];
